-- Step-1. Database creation
-- CREATE DATABASE
CREATE DATABASE IF NOT EXISTS grocery_store;
USE grocery_store;

-- Step-2. Table creation
DROP TABLE IF EXISTS OrderDetails;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS Products;
DROP TABLE IF EXISTS Customers;
DROP TABLE IF EXISTS Store_Employees;
DROP TABLE IF EXISTS Categories;
DROP TABLE IF EXISTS Suppliers;

-- 1. Creating suppliers table
CREATE TABLE suppliers (
    SupplierID TINYINT AUTO_INCREMENT PRIMARY KEY,
    SupplierName VARCHAR(255),
    Address TEXT
);

-- 2. Creating categories table
CREATE TABLE categories (
    CategoryID TINYINT AUTO_INCREMENT PRIMARY KEY,
    CategoryName VARCHAR(255)
);

-- 3. Creating store_employees table
CREATE TABLE store_employees (
    EmployeeID TINYINT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255),
    HireDate VARCHAR(50)
);

-- 4. Creating customers table
CREATE TABLE customers (
    CustomerID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255),
    Address TEXT
);

-- 5. Creating products table
CREATE TABLE products (
    ProductID TINYINT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255),
    SupplierID TINYINT,
    CategoryID TINYINT,
    Price DECIMAL(10,2),
    FOREIGN KEY (SupplierID) REFERENCES suppliers(SupplierID)
		ON UPDATE CASCADE ON DELETE CASCADE, 
    FOREIGN KEY (CategoryID) REFERENCES categories(CategoryID)
		ON UPDATE CASCADE ON DELETE CASCADE
); -- Foreign keys + cascade

-- 6. Creating orders table
CREATE TABLE orders (
    OrderID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    CustomerID SMALLINT,
    EmployeeID TINYINT,
    OrderDate VARCHAR(50),
    FOREIGN KEY (CustomerID) REFERENCES customers(CustomerID)
		ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (EmployeeID) REFERENCES store_employees(EmployeeID)
		ON UPDATE CASCADE ON DELETE CASCADE
); -- Foreign keys + cascade

-- 7. Creating Order_Details table
CREATE TABLE order_details (
    OrderDetailID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    OrderID SMALLINT,
    ProductID TINYINT,
    Quantity TINYINT,
    PriceEach DECIMAL(10,2),
    TotalPrice DECIMAL(10,2),
    FOREIGN KEY (OrderID) REFERENCES orders(OrderID)
		ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (ProductID) REFERENCES products(ProductID)
		ON UPDATE CASCADE ON DELETE CASCADE
); -- Foreign keys + cascade

-- CHECKING TABLES
SHOW TABLES;

-- Step-3. Importing and verifying data
SELECT * FROM Categories;
SELECT * FROM Customers;
SELECT * FROM store_employees;
SELECT * FROM Orders;
SELECT * FROM Suppliers;
SELECT * FROM Products;
SELECT * FROM Order_Details;

SELECT COUNT(*) FROM Categories;
SELECT COUNT(*) FROM Customers;
SELECT COUNT(*) FROM Store_Employees;
SELECT COUNT(*) FROM Orders;
SELECT COUNT(*) FROM Suppliers;
SELECT COUNT(*) FROM Products;
SELECT COUNT(*) FROM Order_Details;

-- ANALYSIS QUERIES
-- 1. Customer Insights
-- Total Unique Customers
SELECT COUNT(DISTINCT CustomerID) AS total_customers 
	   FROM orders;
-- result: 156 customers

-- Top 5 Customers with Highest Number of Orders
SELECT c.Name, COUNT(o.OrderID) AS total_orders
	FROM customers c
JOIN orders o ON c.CustomerID = o.CustomerID
GROUP BY c.Name
ORDER BY total_orders DESC
LIMIT 5;

-- Total and Average Purchase Value per Customer
SELECT c.Name,
	   SUM(od.TotalPrice) AS total_spent,
       AVG(od.TotalPrice) AS avg_spent
	FROM customers c
JOIN orders o ON c.CustomerID = o.CustomerID
JOIN order_details od ON o.OrderID = od.OrderID
GROUP BY c.Name;

-- Top 5 customers by total purchase amount
SELECT c.name,
	   SUM(od.TotalPrice) AS total_spent
	FROM customers c
JOIN orders o ON c.CustomerID = o.CustomerID
JOIN order_details od ON o.OrderID = od.OrderID
GROUP BY c.Name
ORDER BY total_spent DESC
LIMIT 5;

-- 2. Product Performance
-- Number of Products in Each Category
SELECT c.CategoryName, 
	   COUNT(p.ProductID)
	FROM categories c
JOIN products p ON c.CategoryID = p.CategoryID
GROUP BY c.CategoryName;

-- Average Price of Products by Category
SELECT c.CategoryName,
	   AVG(p.Price) AS Avg_Price
	FROM categories c
JOIN products p ON c.CategoryID = p.CategoryID
GROUP BY c.CategoryName;

-- Top 5 Best-Selling Products (by Quantity)
SELECT p.Name, 
	   SUM(od.Quantity) AS total_sold
	FROM products p
JOIN order_details od ON p.ProductID = od.ProductID
GROUP BY p.Name
ORDER BY total_sold DESC
LIMIT 5;

-- Total Revenue Generated by Each Product
SELECT p.Name, 
	   SUM(od.TotalPrice) AS revenue
	FROM products p
	JOIN order_details od ON p.ProductID = od.ProductID
	GROUP BY p.Name
	ORDER BY revenue DESC;
    
-- Variation of Product Sales by Category and Supplier
SELECT c.CategoryName,
       s.SupplierName,
       SUM(od.Quantity) AS Total_Quantity_Sold,
       SUM(od.TotalPrice) AS Total_Revenue
	FROM order_details od
JOIN products p ON od.ProductID = p.ProductID
JOIN categories c ON p.CategoryID = c.CategoryID
JOIN suppliers s ON p.SupplierID = s.SupplierID
GROUP BY c.CategoryName, s.SupplierName
ORDER BY Total_Revenue DESC;

-- 3. Sales Trends
-- Total Number of Orders
SELECT COUNT(*) AS total_orders 
	FROM orders;

-- Average Order Value
SELECT AVG(TotalPrice) AS avg_order_value 
	FROM order_details;

-- Orders Count by Date (Peak Order Dates)
SELECT OrderDate, 
	   COUNT(OrderID) AS orders_count
	FROM orders
GROUP BY OrderDate
ORDER BY orders_count DESC
LIMIT 2;

-- monthly trends in order volume and revenue
SELECT DATE_FORMAT(STR_TO_DATE(OrderDate, '%m/%d/%Y'), '%Y-%m') AS Month,
	   COUNT(DISTINCT o.OrderID) AS Total_Orders,
       SUM(od.TotalPrice) AS Total_Revenue
	FROM orders o
JOIN order_details od ON o.OrderID = od.OrderID
GROUP BY Month
ORDER BY Month;
   
-- Variation in order patterns across weekdays and weekends
SELECT CASE WHEN DAYOFWEEK(STR_TO_DATE(OrderDate, '%m/%d/%Y')) IN (1,7)
			THEN 'Weekend'
			ELSE 'Weekday'
       END AS Day_Type,
	   COUNT(od.OrderID) AS Total_Orders,
	   SUM(od.TotalPrice) AS Total_Revenue
	FROM orders o
JOIN order_details od ON o.OrderID = od.OrderID
GROUP BY Day_Type;

-- 4. Supplier Contribution
-- Total Number of Suppliers
SELECT COUNT(*) AS supplier_count
	from suppliers;

-- Supplier providing most number of products
SELECT SupplierName, 
	   COUNT(ProductID) as Products_count
	FROM suppliers s
JOIN products p ON s.SupplierID = p.SupplierID
GROUP BY SupplierName
ORDER BY products_count DESC
LIMIT 1;

-- Average Price of Products from Each Supplier
SELECT s.SupplierName,
	   AVG(p.Price) AS Avg_Product_Price
	FROM suppliers s
JOIN products p ON s.SupplierID = p.SupplierID
GROUP BY s.SupplierName;

-- Which suppliers contribute the most to total product sales (by revenue)?
SELECT s.SupplierName,
       SUM(od.TotalPrice) AS Total_Revenue,
       ROUND(
			 (SUM(od.TotalPrice) / 
			 (SELECT SUM(TotalPrice) 
				FROM order_details)
			 ) * 100, 2
			) AS Revenue_Percentage
	FROM suppliers s
JOIN products p ON s.SupplierID = p.SupplierID
JOIN order_details od ON p.ProductID = od.ProductID
GROUP BY s.SupplierName
ORDER BY Total_Revenue DESC
LIMIT 1;

-- 5. Employee Performance
-- Number of Employees who have processed Orders
SELECT COUNT(DISTINCT EmployeeID) AS Total_Employees
	FROM orders;

-- Top 3 Employees who handled most of the Orders
SELECT e.Name,
       COUNT(o.OrderID) AS Total_Orders
	FROM store_employees e
JOIN orders o ON e.EmployeeID = o.EmployeeID
GROUP BY e.Name
ORDER BY Total_Orders DESC
LIMIT 3;

-- total sales value processed by each employee
SELECT e.Name,
       SUM(od.TotalPrice) AS Total_Sales
	FROM store_employees e
JOIN orders o ON e.EmployeeID = o.EmployeeID
JOIN order_details od ON o.OrderID = od.OrderID
GROUP BY e.Name
ORDER BY Total_Sales DESC;

-- Average Order value handled by Each Employee
SELECT e.Name,
       AVG(od.TotalPrice) AS Avg_Order_Value
	FROM store_employees e
JOIN orders o ON e.EmployeeID = o.EmployeeID
JOIN order_details od ON o.OrderID = od.OrderID
GROUP BY e.Name;

-- Relationship between Quantity Ordered and Total Price
SELECT MAX(Quantity),
       AVG(TotalPrice) AS Avg_Total_Price
	FROM order_details
GROUP BY Quantity
ORDER BY Quantity;
-- Insight: total price increases with increasing quantity

-- average quantity ordered per product
SELECT p.Name,
       AVG(od.Quantity) AS Avg_Quantity
	FROM products p
JOIN order_details od ON p.ProductID = od.ProductID
GROUP BY p.Name;

-- 
SELECT p.Name AS Product_Name,
       MIN(od.PriceEach) AS Min_Price,
       MAX(od.PriceEach) AS Max_Price,
       AVG(od.PriceEach) AS Avg_Price
	FROM products p
JOIN order_details od
    ON p.ProductID = od.ProductID
GROUP BY p.Name;
-- Insight: No Variation in prices 

-- EER DIAGRAM
-- supplier → products
-- categories → products
-- customers → orders
-- employees → orders
-- orders → order_details
-- products → order_details

-- Advanced
-- 1. Monthly Revenue Trend
-- Monthly Revenue
SELECT 
SUBSTRING(OrderDate, 1, 7) AS month,
SUM(od.TotalPrice) AS total_revenue
FROM orders o
JOIN order_details od ON o.OrderID = od.OrderID
GROUP BY month;

-- 2. Top 3 Highest Revenue Customers
-- Top Customers by Revenue
SELECT c.Name,
SUM(od.TotalPrice) AS total_spent
FROM customers c
JOIN orders o ON c.CustomerID = o.CustomerID
JOIN order_details od ON o.OrderID = od.OrderID
GROUP BY c.Name
ORDER BY total_spent DESC
LIMIT 3;

-- 3. Category-wise Revenue
-- Revenue by Category
SELECT c.CategoryName,
SUM(od.TotalPrice) AS revenue
FROM categories c
JOIN products p ON c.CategoryID = p.CategoryID
JOIN order_details od ON p.ProductID = od.ProductID
GROUP BY c.CategoryName;

-- 4. Most Active Employee
-- Top Employee
SELECT e.Name,
COUNT(o.OrderID) AS orders_handled
FROM employees e
JOIN orders o ON e.EmployeeID = o.EmployeeID
GROUP BY e.Name
ORDER BY orders_handled DESC
LIMIT 1;

-- 5. Average Quantity per Order
-- Avg Quantity per Order
SELECT OrderID,
AVG(Quantity) AS avg_qty
FROM order_details
GROUP BY OrderID;

-- More Advanced
-- 1. Top Selling Category
-- Top Category by Sales
SELECT c.CategoryName,
SUM(od.Quantity) AS total_sold
FROM categories c
JOIN products p ON c.CategoryID = p.CategoryID
JOIN order_details od ON p.ProductID = od.ProductID
GROUP BY c.CategoryName
ORDER BY total_sold DESC
LIMIT 1;

-- 2. Orders on Weekends vs Weekdays
-- Weekday vs Weekend Orders
SELECT 
CASE 
WHEN DAYOFWEEK(STR_TO_DATE(OrderDate,'%m/%d/%Y')) IN (1,7)
THEN 'Weekend'
ELSE 'Weekday'
END AS day_type,
COUNT(*) AS total_orders
FROM orders
GROUP BY day_type;

-- 3. Highest Single Order Value
-- Highest Order Value
SELECT OrderID, SUM(TotalPrice) AS order_value
FROM order_details
GROUP BY OrderID
ORDER BY order_value DESC
LIMIT 1;

-- DATABASE + TABLE PROOF
-- DATABASE CREATED
SHOW DATABASES;
-- TABLES CREATED
SHOW TABLES;
-- DATA IMPORT PROOF
-- CUSTOMERS DATA
SELECT * FROM customers LIMIT 25;
-- PRODUCTS DATA
SELECT * FROM products LIMIT 25;
-- ORDERS DATA
SELECT * FROM orders LIMIT 25;
-- ORDER_DETAILS DATA
SELECT * FROM order_details LIMIT 25;


